baseURL = "https://Tiennnn1107.github.io/TranTanTien-blog/"
publishDir = "docs"
languageCode = "vi-vn"
title = "Tr·∫ßn T·∫•n Ti·∫øn | Developer"
theme = "PaperMod"

[pagination]
  pagerSize = 8

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    noClasses = false
    style = "dracula"
    lineNos = true

[params]
  env = "production"
  author = "Tr·∫ßn T·∫•n Ti·∫øn"
  description = "Sinh vi√™n CNTT | Developer | Ch·∫≠m c≈©ng ƒë∆∞·ª£c, kh√¥ng d·ª´ng l·∫°i l√† ƒë∆∞·ª£c."
  keywords = ["Developer", "Java", "Spring Boot", "Backend", "Portfolio"]

  # Giao di·ªán (C·ªê ƒê·ªäNH)
  defaultTheme = "dark"
  disableThemeToggle = true   # üî• T·∫ÆT H·∫≤N NG√ÄY / ƒê√äM
  disableSpecial1stPost = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  ShowShareButtons = false


  assets = { disableFingerprinting = true }

  # ===== PROFILE MODE (HOME) =====
  [params.profileMode]
    enabled = true
    title = "Tr·∫ßn T·∫•n Ti·∫øn"
    subtitle = "Developer | Ch·∫≠m c≈©ng ƒë∆∞·ª£c, kh√¥ng d·ª´ng l·∫°i l√† ƒë∆∞·ª£c."
    imageUrl = "images/avartar.jpg"
    imageWidth = 380
    imageHeight = 380
    imageTitle = "Tr·∫ßn T·∫•n Ti·∫øn"

    [[params.profileMode.buttons]]
      name = "B√†i Vi·∫øt"
      url = "posts"

    [[params.profileMode.buttons]]
      name = "ABOUT"
      url = "about"

  # Social icons (khuy·∫øn ngh·ªã)
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/Tiennnn1107"

# ===== MENU =====
[menu]

  [[menu.main]]
    identifier = "home"
    name = "HOME"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "POSTS"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "ABOUT"
    url = "/about/"
    weight = 3
