baseURL = "https://Tiennnn1107.github.io/TranTanTien-blog/"
publishDir = "docs"
relativeURLs = true
canonifyURLs = true
languageCode = "vi"
title = "Blog lập trình của Trần Tấn Tiến"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
